name: Build wlroots for Termux

on:
  workflow_dispatch:
  push:
    branches: [wlroots-display-client]
	   push:
    branches: [wlroots-display-client]
  pull_request:
    branches: [wlroots-display-client]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone termux-packages
      uses: actions/checkout@v4
      with:
        repository: termux/termux-packages
        path: termux-packages

    - name: Clone wlroots into x11-packages
      run: |
        mkdir -p termux-packages/x11-packages/wlroots-termux
        cd termux-packages/x11-packages/wlroots-termux
        curl -LO https://github.com/xodiosx/wlroots/archive/refs/heads/wlroots-display-client.tar.gz
        SHA256=$(sha256sum wlroots-display-client.tar.gz | cut -d' ' -f1)
        cat > build.sh <<EOF
		TERMUX_PKG_HOMEPAGE=https://gitlab.freedesktop.org/wlroots/wlroots
		TERMUX_PKG_DESCRIPTION="Modular Wayland compositor library"
		TERMUX_PKG_LICENSE="MIT"
		TERMUX_PKG_MAINTAINER="@xodiosx"
		TERMUX_PKG_VERSION=0.18.2
		TERMUX_PKG_SRCURL=https://github.com/xodiosx/wlroots/archive/refs/heads/wlroots-display-client.tar.gz
		TERMUX_PKG_SHA256=$SHA256
		TERMUX_PKG_DEPENDS="libdrm, libglvnd, libwayland, libxcb, libxkbcommon, xcb-util-renderutil, xcb-util-wm, termux-gui-c, termux-display-client"
		TERMUX_PKG_BUILD_DEPENDS="libglvnd-dev, libwayland-protocols"
		TERMUX_PKG_RECOMMENDS="xwayland"
		TERMUX_PKG_BREAKS="sway (<< 1.10)"
		TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
		  -Dexamples=false
		  -Dxwayland=enabled
		  -Dsession=disabled
		  -Dbackends=x11,termuxgui,termuxdc
		  -Drenderers=gles2,vulkan
		"
		termux_step_pre_configure() {
		  export CPPFLAGS+=" -Wno-alloca -Wno-strict-prototypes"
		}
		EOF

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip android-ndk-r27c-linux.zip -d $HOME
        echo "NDK=$HOME/android-ndk-r27c" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget unzip build-essential clang \
          automake autoconf libtool pkg-config ninja-build \
          cmake libdrm-dev libxkbcommon-dev libpixman-1-dev \
          python3 python3-pip python3-setuptools curl

    - name: Setup Termux build env
      working-directory: termux-packages
      run: ./scripts/setup-android-cross-env.sh

    - name: Build wlroots .deb
      working-directory: termux-packages
      run: |
        source ./scripts/properties.sh
        ./build-package.sh -a aarch64 wlroots-termux

    - name: Upload DEB
      uses: actions/upload-artifact@v4
      with:
        name: wlroots-termux-deb
        path: termux-packages/output/*.deb
