name: Build XWlroot wlroots-display-client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          meson ninja-build \
          clang pkg-config \
          libpixman-1-dev \
          libwayland-dev \
          wayland-protocols \
          libegl1-mesa-dev \
          libdrm-dev \
          libxkbcommon-dev \
          libgbm-dev \
          libudev-dev \
          libinput-dev \
          libxcb1-dev \
          libxcb-render0-dev \
          libxcb-shm0-dev \
          libxcb-xfixes0-dev

    - name: Clone XWlroot repo (wlroots-display-client branch)
      run: |
        git clone https://github.com/xodiosx/XWlroot.git --branch wlroots-display-client --depth=1
        ls -l XWlroot

    - name: Setup and build with Meson/Ninja
      working-directory: XWlroot/wlroots
      run: |
        meson setup build \
          --buildtype release \
          -Drenderer=pixman \
          -Dbackends=termuxdc \
          -Dwerror=false

        ninja -C build

    - name: Archive build output
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: wlroots-binaries
        path: |
          XWlroot/wlroots/build/
