# .github/workflows/build-xwlroot.yml
name: Build XWlroot

on:
  workflow_dispatch:

jobs:
  build-xwlroot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential meson ninja-build \
            wayland-protocols libwayland-dev libdrm-dev \
            libegl1-mesa-dev libgbm-dev libxkbcommon-dev \
            libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev \
            pkg-config cmake libinput-dev

      - name: Set up environment
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Configure wlroots with meson
        run: |
          git clone https://github.com/xodiosx/XWlroot.git --depth=1
          cd XWlroot/wlroots
          meson setup build \
            --buildtype release \
            -Drenderer=pixman \
            -Dbackends=termuxdc \
            -Dwerror=false

      - name: Build wlroots
        run: |
          cd XWlroot/wlroots/build
          ninja

      - name: Archive built files
        uses: actions/upload-artifact@v4
        with:
          name: wlroots-artifacts
          path: XWlroot/wlroots/build
