name: Build wlroots2

on:
  workflow_dispatch:
  push:
    branches: [wlroots-display-client]
  pull_request:
    branches: [wlroots-display-client]
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: xodiosx/wlroots
        ref: wlroots-display-client
        submodules: recursive
               
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install meson -y
        curl -L https://wrapdb.mesonbuild.com/v2/wayland-protocols_1.35/get_wrap -o subprojects/wayland-protocols.wrap       
        meson wrap update --force
        
        sudo apt install -y \
          ninja-build \
          clang pkg-config \
          libpixman-1-dev \
          libwayland-dev \
          wayland-protocols \
          libegl1-mesa-dev \
          libdrm-dev \
          libxkbcommon-dev \
          libgbm-dev \
          libudev-dev \
          libinput-dev \
          libxcb1-dev \
          libxcb-render0-dev \
          libxcb-shm0-dev \
          libxcb-xfixes0-dev


    - name: Configure build
      run: |
        ls
        
        meson setup build \
          --buildtype release \
          -Drenderers=auto \
          -Dbackends=termuxdc \
          -Dwerror=false 
          

        ninja -C build

    - name: Archive build output
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: wlroots-binaries
        path: |
          wlroot/build/
